config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  get "/search" => "home#search"

  resources :sessions, only: [:new, :create, :destroy]

  resources :bookings

  resources :users do
    resources :bookings, only: [:show]
  end

  resources :rides do
    resources :bookings
    delete 'completed' => "rides#complete"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :rides
  has_many :bookings
  has_many :reviews

  # ========> General validation <=========
  validates :first_name, :last_name, :gender, :date_of_birth, presence: true
  validates :phone_number, presence: true
  validate :min_age

  # ========> for sorcery <=========
  authenticates_with_sorcery!

  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true, presence: true # AY: Added presence validation

  # ========> for paperclip <=======
  has_attached_file :avatar, styles: { medium: "250x250>", thumb: "100x100>" }, default_url: "circle_arrow2.png"
  validates_attachment_content_type :avatar, content_type: /^image\/(jpg|jpeg|pjpeg|png|x-png)$/, :message => 'Only jpeg and png files please!'
  validates_with AttachmentSizeValidator, attributes: :avatar, less_than: 3.megabytes



  def age
    if Date.today >= date_of_birth
      age = Date.today.year - date_of_birth.year
    else
      age = Date.today.year - date_of_birth.year - 1
    end
      age
  end

  private

  def min_age
      if date_of_birth.nil? || date_of_birth > 18.years.ago
      errors.add(:date_of_birth, "should be at least 18 years ago from today")
      end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # before_action :require_login, only: :show
  def new
    @user = User.new
  end

  def show
    @alt_color = true
    @user = User.find(params[:id])
    @rides = @user.rides

    @total_rating = [4]
    @rides.each do |ride|
      ride.bookings.each do |booking|
        unless booking.rating.nil?
          @total_rating << booking.rating
        end
      end
    end

      @average_rating = @total_rating.compact.inject(:+) / @total_rating.length
  end

  def create
    @user = User.new(user_params)

    if @user.save
      UserMailer.welcome(@user).deliver_later
      session[:user_id] = @user.id
      redirect_to @user, alert: "Thanks for signing up to Hitchr, #{@user.first_name}!"
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      redirect_back_or_to(root_path)
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def destroy
   @user = User.find(params[:id])
   UserMailer.deleted_user(@user).deliver_later
   @user.rides.delete_all
   @user.bookings.delete_all
   @user.destroy
   flash[:success] = "User deleted"
   redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :gender, :date_of_birth, :reliability, :avatar, :phone_number)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="row">
    <div class="col-lg-12 text-center">
      <div class="signup"><h1>Sign up for Hitchr</h1></div>
      <b />


      <% unless @user %>
        <% @user = User.new %>
      <% end %>

      <div class="user-form-errors">
        <% if @user.errors.any? %>
          <p>Oops! We couldn't process your submission. Please check your entries and try again.</p>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
      <br />
      <div class="user-form">
        <!-- # use Parsley gem/jquery library to do form validations  -->
        <%= form_for @user, html: {"data-parsley-validate" => ''} do |f| %>

          <div class="field">
            <%= f.label :first_name %> <br />
            <%= f.text_field :first_name, "data-parsley-trigger" => "blur", :required => "",
            "data-parsley-required-message" => "Please enter your first name." %>
          </div>

          <div class="field">
            <%= f.label :last_name %> <br />
            <%= f.text_field :last_name, "data-parsley-trigger" => "blur", :required => "",
            "data-parsley-required-message" => "Please enter your last name." %>
          </div>

          <div class="field">
            <%= f.label :gender %> <br />
            <%= f.select :gender, [['Male','Male'],['Female','Female'], ['Other','Other']],
            "data-parsley-trigger" => "blur", :required => "" %>
          </div>

          <div class="field">
            <%= f.label :date_of_birth %> <br />
            <%= f.date_select :date_of_birth, start_year: Date.today.year - 18, end_year: 1940,
            "data-parsley-trigger" => "blur", :required => "",
            "data-parsley-required-message" => "Please enter your birthday." %>
            <p class="form_warning">You must be at least 18 years old to sign up!</p>
          </div>

          <div class="field">
            <%= f.label :email %> <br />
            <%= f.text_field :email, "data-parsley-type" => "email",
            "data-parsley-trigger" => "blur", :required => "",
            "data-parsley-required-message" => "Please enter your email address.",
            "data-parsley-type-message" => "Oops! There seems to be a typo! Please try again." %>
          </div>

          <div class="field">
            <%= f.label :phone_number %> <br />
            <%= f.text_field :phone_number, :placeholder => "416 123 4567",
            "data-parsley-pattern" => "^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}$",
            "data-parsley-trigger" => "blur",
            "data-parsley-minlength" => "6", :required => "",
            "data-parsley-required-message" => "Please enter your number.",
            "data-parsley-minlength-message" => "Please input at least 6 digits." %>
          </div>

          <div class="field">
             <%= f.label :password %><br />
             <%= f.password_field :password,
             "data-parsley-trigger" => "blur", "data-parsley-minlength" => "6",
              :required => "", "data-parsley-required-message" => "Please enter a password.",
              "data-parsley-minlength-message" => "Please input a password that contains at least 6 characters." %>
          </div>

          <div class="field">
             <%= f.label :password_confirmation %><br />
             <%= f.password_field :password_confirmation,
             "data-parsley-minlength" => "6", "data-parsley-equalto" => "input#user_password", "data-parsley-trigger" => "blur",
             :required => "", "data-parsley-required-message" => "Please confirm your password.",
             "data-parsley-equalto-message" => "Oops! Looks liks your passwords don't match. Please try again." %>
          </div>

          <div class="field">
            <div class="input-group">
              <span class="input-group-btn">
                <span class="btn btn-file">
                 <%= f.label "Choose a picture", class: "btn btn-default btn-file" %><br />
                 <%= f.file_field :avatar, "data-parsley-pattern" => "/\.(jpe?g|png)$/i",
                 class: "btn btn-default btn-file", "data-parsley-pattern-message" =>
                   "jpg/png files only please." %></span>
              </span>
            </div>
          </div>

          <div class="field">
            <%= f.submit "Sign up" %>
          </div>
        <% end %>
      </div>
    </div>
</div>
<!-- /.row -->

app/views/users/edit.html.erb
<div class="show-header">

</div>

<div id="edit_style" class="row">
    <div id="edit_form" class="col-lg-12 text-center">

      <h1 class="edit">Edit Profile</h1>

        <div class="user-form-errors">
          <% if @user.errors.any? %>
            <p>Oops! We couldn't process your submission. Please check your entries and try again.</p>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
        <br />

        <div class="user-form">
          <!-- # use Parsley gem/jquery library to do form validations  -->
          <%= form_for @user, html: {"data-parsley-validate" => ''} do |f| %>

            <div class="field">
              <%= f.label :first_name %> <br />
              <%= f.text_field :first_name, "data-parsley-trigger" => "blur", :required => "",
              "data-parsley-required-message" => "Please enter your first name." %>
            </div>

            <div class="field">
              <%= f.label :last_name %> <br />
              <%= f.text_field :last_name, "data-parsley-trigger" => "blur", :required => "",
              "data-parsley-required-message" => "Please enter your last name." %>
            </div>

            <div class="field">
              <%= f.label :gender %> <br />
              <%= f.select :gender, [['Male','Male'],['Female','Female'], ['Other','Other']],
              "data-parsley-trigger" => "blur", :required => "" %>
            </div>

            <div class="field">
              <%= f.label :date_of_birth %> <br />
              <%= f.date_select :date_of_birth, start_year: Date.today.year - 18, end_year: 1940,
              "data-parsley-trigger" => "blur", :required => "",
              "data-parsley-required-message" => "Please enter your birthday." %>
              <p class="form_warning">You must be at least 18 years old to sign up!</p>
            </div>

            <div class="field">
              <%= f.label :email %> <br />
              <%= f.text_field :email, "data-parsley-type" => "email",
              "data-parsley-trigger" => "blur", :required => "",
              "data-parsley-required-message" => "Please enter your email address.",
              "data-parsley-type-message" => "Oops! There seems to be a typo! Please try again." %>
            </div>

            <div class="field">
              <%= f.label :phone_number %> <br />
              <%= f.text_field :phone_number, :placeholder => "416 123 4567",
              "data-parsley-pattern" => "^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}$",
              "data-parsley-trigger" => "blur",
              "data-parsley-minlength" => "6", :required => "",
              "data-parsley-required-message" => "Please enter your number.",
              "data-parsley-minlength-message" => "Please input at least 6 digits." %>
            </div>

            <div class="field">
              <div class="input-group">
                <span class="input-group-btn">
                  <span class="btn btn-file">
                   <%= f.label "Choose a picture", class: "btn btn-default btn-file" %><br />
                   <%= f.file_field :avatar, "data-parsley-pattern" => "/\.(jpe?g|png)$/i",
                   class: "btn btn-default btn-file", "data-parsley-pattern-message" =>
                     "jpg/png files only please." %></span>
                </span>
              </div>
            </div>

            <div class="field">
              <%= f.submit "Save", :class => "save_button" %>
            </div>
          <% end %>
        </div>
    </div>
</div>

app/views/users/new.html.erb
 <div class="container">
   <%= render "form" %>
 </div>

app/views/users/show.html.erb
<div class="show-header">
</div>
<!-- TABS - DONT SHOW RIDES, BOOKINGS, OR FEEDBACK if you look at someone elses profile -->
<div class="tabs">
  <ul class ="tab-links">
    <li class="active"><a href="#tab1">Profile</a></li>
    <li><a href="#tab2">My Reviews</a></li>
    <% if current_user == @user %>
      <li><a href="#tab3">My Rides</a></li>
      <li><a href="#tab4">My Bookings</a></li>
      <li><a href="#tab5">Ride Feedback</a></li>
    <%end%>
  </ul>

  <div class="tab-content">
  <!--USER PROFILE INFORMATION TAB - and AVERAGE STAR RATING  -->
    <div class="tab active" id="tab1">
      <div class="user_profile">
        <h1 class="user_header"> User Profile</h1>
          <div class="image_div">
            <%= image_tag @user.avatar.url, class: "user-avatar"%><br />
          </div>
          <div class="user_content clearfix">
            <h3 class="rating">Rating</h3>
            <div class="rateYo stars-readonly" data-rating=<%= @average_rating %>></div>
              <% @total_rating.count - 1%>
            <br />

            <div id="user_details">
              <p class="user_name"><%= @user.first_name.capitalize %> <%= @user.last_name.capitalize %><br />
              <%= @user.email %><br />
              <%= @user.gender %><br />
              Age: <%= @user.age %><br />

              <%= number_to_phone(@user.phone_number, area_code: true) %><br>
            </div>
            <div class="user_links">
              <!-- ONLY ALLOW EDIT AND DELETE IF YOU ARE THE USER OF THE USER PROFILE -->
              <% if current_user == @user %>
                <%= link_to "Edit My Account", edit_user_path(@user), class: "edit-button" %><br />
              </br><%= link_to "Delete Account", user_path(@user), class: "cancel-ride-button", :method => :delete, data: {confirm: "Delete User: #{@user.first_name.capitalize} #{@user.last_name.capitalize}?"} %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

  <!--REVIEWS TAB - SHOWS ALL THE REVIEWS and RATIINGS ABOUT THE DRIVER  -->
  <div class="tab" id="tab2">
    <br /> <h4>Reviews about me: </h4>
    <div class="user-reviews-container">

      <% @rides.each do |ride| %>
        <% ride.bookings.each do |booking| %>
          <% if booking.rating && booking.review %>
            <div class="rateYo stars-readonly" data-rating=<%= booking.rating %>></div>
            <%= booking.review %><br><br>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

  <!-- MY RIDES TABS - Offer a ride, or view the rides you have offered -->
  <div class="tab" id="tab3">
    <div class="offer-ride">
      <h2 class="offer-text">Give someone a lift</h2>
      <p class="offer-body">Have some spare seats in the car? Offer a ride to
        save that gas money, cut back on carbon emissions, and make a new
        friend!</p>
          <%= link_to "Offer a Ride", new_ride_path(@user), :class => "offer-button"%><br>
    </div>
    <br /> <h3 id="midline">Rides I'm Offering: </h3>

  <ul>
    <% @rides.reverse.each do |ride| %>
      <% arr = [0] %>
      <% ride.bookings.each { |booking| arr << booking.seats} %>
      <% total_seats = arr.compact.inject(:+) %>

    <div>
        <li class="offered-ride">
          <h4><%= ride.start_location %> - <%= ride.end_location %></h4>

          <p><%= ride.date.strftime("%b %-d, %Y") %> | <%= ride.time.strftime("%-l:%M %p") %></p>
          <p><b>Seats Available: </b><%= ride.seats_available - total_seats < 0 ? 0 : ride.seats_available - total_seats %></p>
          <p><b>Price:</b> $<%= ride.price %></p>

          <% if ride.comments.present? == true %>
            <p id="comment">"<%= ride.comments %>"</p>
          <% elsif ride.comments == false  %>
            <p></p>
          <% end %>

          <p id="status"><b>Status: </b> <%= ride.completed ? "Ride Complete" : "Ride Pending" %></p>
          <!-- Cancel a ride if its not complete already, or Ride Complete to finish the ride (if its on the same day) -->
          <% if ride.completed == false %>
            <%= link_to "Cancel Ride", ride_path(ride), :method => :delete, :class => "cancel-ride-button" %><br /><br />
            <%# if ride.date < Date.today %>
              <%= link_to "Ride Complete", ride_completed_path(ride), :method => :delete, :class => "ride-complete-button" %><br />
            <%# end %>
          <% end %>
          <br />
            <h5 id="hitches">Hitches on this ride: </h5>
            <ul>
                <li>

                <% if ride.bookings.any? %>
                  <% ride.bookings.each do |booking| %>
                    <p><%= link_to booking.user.first_name.capitalize, booking.user, :class => "seat-booker-button" %></p>
                    <p>Seats booked: <%=  booking.seats %></p>
                    <p>Booking date: <%=  booking.created_at.strftime("%b %-d, %Y")%> | <%= booking.created_at.strftime("%-l:%M %p") %></p>
                      <% if ride.completed == false %>
                        <%= link_to "Decline Booking", booking_path(booking), :method => :delete, :class => "reject-button" %><br />
                      <% end %>
                    <% end %>
                  <% else  %>
                    <p id="sorry">Sorry, nobody's booked a seat yet!</p>
                <% end %>
              </li><br><br>
          </ul>
        </li>
      </div>
    <% end %>
    </ul>
  </div>

    <!-- BOOKINGS TAB - IF BOOKING EXISTS AND RIDE IS NOT COMPLETE -->
    <div class="tab" id="tab4">
      <br /><h3>My Bookings: </h3>
      <ul>
        <% @user.bookings.each do |booking| %>
          <% if booking.ride && booking.ride.completed == false %>
              <li class="bookings-show"><h4><b><%= booking.ride.start_location %> to <%= booking.ride.end_location %></b></h4>
                <% if booking.ride.user %>
                  <p><b>Your Driver:</b> <%= booking.ride.user.first_name.capitalize %> <%= booking.ride.user.last_name.capitalize %><br>
                <% end %>
                     <b>Date:</b> <%= booking.ride.date.strftime("%b %-d, %Y") %> | <%= booking.ride.time.strftime("%-l:%M %p")  %> <br>
                     <b>Seats You Requested:</b> <%= booking.seats %></p></br>
                     <p><%= link_to "View Ride Details", booking.ride, :class => "view-ride-button" %></p><br />
                <!-- You cant cancel someone elses booking -->
                <% if current_user == booking.user %>
                  <%= link_to "Cancel Booking", booking_path(booking), :method => :delete, :class => "cancel-ride-button" %><br />
                <% end %>

            </li><br><br>
            <% end %>
         <% end %>
       </li>
      </ul>
      <%= link_to "Hitch a new ride!", root_path, :class => "view-ride-button" %><br />
    </div>

    <!-- After ride is complete, booking moves here for rider to leave feedback about driver -->
    <div class="tab" id="tab5">
      <br /><h4>Ride Feedback: </h4>
        <% @user.bookings.each do |booking| %>
          <% if booking.ride && booking.ride.completed? %>
          <ul>
            <li><h5><b><%= booking.ride.start_location %> to <%= booking.ride.end_location %></b></h5>
              <% if booking.ride.user %>
                <p><b>Your Driver:</b> <%= link_to "#{booking.ride.user.first_name.capitalize} #{booking.ride.user.last_name.capitalize}", user_path(booking.ride.user) %><br>
                <% end %>
                 <b>Date:</b> <%= booking.ride.date.strftime("%b %-d, %Y") %><br>
                 <b>Seats You Requested:</b> <%= booking.seats %></p><br>
                  <!-- Leave a review if you haven't already -->
                  <% unless booking.review %>
                    <%= form_for booking, method: :put do |f| %>
                      <div class="rateYo">
                      </div>
                        <%= f.hidden_field :rating, id: "set-rating" %>
                      <div class="field">
                        <%= f.text_field :review, placeholder: "Leave a Review"%>
                      </div>
                      <div class="actions">
                        <%= f.submit "Submit Review" %>
                      </div>
                    <% end %>
                  <% end %>
              </li><br><br>
            </ul>
            <% end %>
        <% end %>
    </div>
  </div>
</div>