config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  get "/search" => "home#search"

  resources :sessions, only: [:new, :create, :destroy]

  resources :bookings

  resources :users do
    resources :bookings, only: [:show]
  end

  resources :rides do
    resources :bookings
    delete 'completed' => "rides#complete"
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index
    @user = current_user || User.new
    @rides = Ride.limit(4)
    search
  end

  def search
    if (params[:start_location] && params[:end_location]) && params[:date]
      @rides = Ride.search(params[:start_location], params[:end_location], params[:date]).order("created_at DESC")
      respond_to do |format|
        format.html { render partial: 'search' }
        format.json { render json: @rides }
      end
    else
      render :index
    end
  end



end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_search.html.erb
<% if @rides.any? %>
  <% @rides.reverse.each do |ride| %>
    <% unless ride.completed == true %>
      <div class="grid">
        <figure class="effect-sadie">
          <figcaption>
            <h2>Departs: <%= ride.date.strftime("%b %-d, %Y") %> at
              <%= ride.time.strftime("%-l:%M %p") %><br><b>$<%= ride.price %></b><br>
                <%= ride.start_location %> &#8594 <%= ride.end_location %></h2>
            <p>Driver: <%= ride.user.first_name %></p>
            <a href="<%= ride_path(ride) %>">View Ride</a>
          </figcaption>
        </figure>
      </div>
    <%end%>
  <%end%>

<% else %>
  <h2 class="search-empty">Sorry, there aren't any rides available for either this time or location. Try broadening your search!</h2>
<%end%>

app/views/home/index.html.erb
<!-- First slide  -->
    <div id="outer-wrap" style="width: 100%; height: 640px;">
      <div id="video-wrap" class="video-wrap">
          <video id="my-video" preload="metadata" autoplay loop>
              <source src="<%= asset_path 'NewVideo2.mp4' %>" type="video/mp4">
              <source src="<%= asset_path 'NewVideo2.ogv' %>" type="video/ogv">
              <source src="<%= asset_path 'NewVideo2.webm' %>" type="video/webm">
          </video>
          <div class="content-container">
            <div class="content-overlay">
                <div class="title"><%= image_tag('title.png')%></div>
                <h3 id="tagline">Book an empty seat with a trusted driver, headed your way.</h3>
            </div>
            <div id="search-form" >
              <%= form_tag search_path, method: "get", class: "search" do %>



                <div class="search_wrap" id="start_location_wrap">
                  <div class="search_wrap_icon"><%= image_tag "Start_4Real.png" %></div>
                  <%= text_field_tag :start_location, params[:start_location], placeholder: "Start City" %>
                </div>

                <div class="search_wrap" id="end_location_wrap">
                  <div class="search_wrap_icon"><%= image_tag "end_for_real.png" %></div>
                  <%= text_field_tag :end_location, params[:end_location], placeholder: "End City" %>
                </div>


              <%= date_field :date, params[:date], min: Date.today, include_blank: true, class: 'date-search', placeholder: "yyyy-mm-dd" %>

              <div id="search_date_wrap">
                <%= submit_tag "Search", name: nil, class: "search-button" %>
                <% end %>
              </div>

            </div>

          </div>
      </div>
    </div>
    <!-- first slide end  -->


    <!-- second slide  -->
    <div id="content_1" class="content" >
      <div class="wall2-info-container">
      <h2 class="info-1">Trek across Canada</h2>
      <h3 class="info-3">From campus to home, city to town</h3>
      </div>
      <h3 class="info-3" id="description">Mid to long-distance ridesharing made easy</h2>

      <div class="all-icons">
          <div class="icon-home"><%= image_tag('save_money.png', :class => "icon_styling-1")%>
          </br><h3 class="icon"><span>SAVE MONEY</span></br> As a Driver or a Passenger</h3>
          </div>
          <div class="icon-home"><%= image_tag('search.png', :class => "icon_styling-2")%>
          </br><h3 class="icon"><span>FIND &amp OFFER A RIDE</span></br> Whenever you want, wherever you want</h3>
          </div>
          <div class="icon-home"><%= image_tag('trust.png', :class => "icon_styling-3")%>
          </br><h3 class="icon"><span>CHOOSE</span></br> A trusted, community-reviewed travel buddy</h3>
          </div>
      </div>



    </div>

 <!--  second wall end  -->

<!-- third wall  -->
    <div class="parallax-container" data-parallax="scroll" data-position="top" data-bleed="10" data-image-src="<%= asset_path "secondhp.jpg" %>" data-natural-width="1400" data-natural-height="900" style="height: 446px;"></div>
    <!-- third wall end -->

    <!-- fourth wall  -->
    <div id="content_2" class="content" >
    <div class="wall2-info-container">
      <h1 class="placeholder-text">Check out some recent rides offered : </h1>
    </div>
    <div class="ride-list">
      <!-- Search results go here -->
    </div>

    <div class="placeholder-info">
      <% @rides.reverse.each do |ride| %>
        <div class="grid">
          <figure class="effect-sadie">
            <figcaption>
              <h2>Departs: <%= ride.date.strftime("%b %-d, %Y") %> at
                <%= ride.time.strftime("%-l:%M %p") %><br><b>$<%= ride.price %></b><br>
              <%= ride.start_location %> &#8594 <%= ride.end_location %></h2>
              <p>Driver: <%= ride.user.first_name %></p>
              <a href="<%= ride_path(ride) %>">View Ride</a>
            </figcaption>
          </figure>
        </div>
      <%end%>
    </div>
  </div>
    <!-- fourth wall end  -->

app/views/home/search.html.erb
<%= render 'search' %>