config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  get "/search" => "home#search"

  resources :sessions, only: [:new, :create, :destroy]

  resources :bookings

  resources :users do
    resources :bookings, only: [:show]
  end

  resources :rides do
    resources :bookings
    delete 'completed' => "rides#complete"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
  <head>
    <title>Hitchr</title>
    <script src="http://maps.googleapis.com/maps/api/js?key=<%= ENV["gmaps_api_key"] %>&libraries=places"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Raleway:400,900,700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <meta name="description" content="">
     <meta name="author" content="">




     <title>Bare - Start Bootstrap Template</title>

     <!-- Bootstrap Core CSS -->

     <!-- Custom CSS -->
     <style>
     body {
         padding-top: 31px;
         /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
     }
     </style>

     <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
     <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
     <!--[if lt IE 9]>
         <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
         <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
     <![endif]-->
  </head>
  <body class="<%= @alt_color ? 'background' : ''%>">
    <div class="popup" data-popup="popup-1">
      <div class="popup-inner2">
          <%= render partial: "sessions/form", object: @user %>
          <a data-popup-close="popup-1" href="#"></a>
          <a class="popup-close" data-popup-close="popup-1" href="#1">x</a>
      </div>
      </div>

    <div class="popup" data-popup="popup-2">
        <div class="popup-inner">
              <%= render partial: "users/form", object: @user %>
            <a data-popup-close="popup-2" href="#"></a>
            <a class="popup-close" data-popup-close="popup-2" href="#2">x</a>
        </div>
    </div>

    <header>

      <!-- Navigation -->
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" style="margin-bottom: 0;">
        <div class="container">

          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><img class="image_class" src="<%= asset_path "Untitled-1.png"%>" alt="Hitchr" width="100px" /></a>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <% if current_user %>
              <li>
                <%= link_to "Logout", session_path("current"), :method => :delete %>
              </li>
              <li>
                <%= link_to current_user.first_name, user_path(current_user) %>
              </li>
              <% else %>
              <li>
                <a class="btn" data-popup-open="popup-1" href="#1">
                  <%# link_to "Log in", new_session_path  %>
                  Log in
                </a>
              </li>
              <li>
                <a class="btn" data-popup-open="popup-2" href="#2">
                  <%# link_to "Sign up", new_user_path %>
                  Sign up
                </a>
              </li>
              <% end %>
            </ul>
          </div>
          <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
        <div class="login-error"><%= flash[:error] %></div>


      </nav>

    </header>

  <%= yield %>

  <footer></footer>

  </body>
</html>